version: '{build}'
shallow_clone: true

matrix:
  fast_finish: true

environment:
  matrix:
    - perl_type: cygwin
    - perl_type: activestate
    - perl_type: strawberry
      perl_version: 5.26.1.1
    - perl_type: strawberry
      perl_version: 5.24.3.1
    - perl_type: strawberry
      perl_version: 5.22.3.1
    - perl_type: strawberry
      perl_version: 5.20.3.3

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --installdeps -n --with-develop --with-recommends .'

build: off

test_script:
  - '%cpanm% --test-only -v .'
